/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Diff two packages
 * source implement from cnpmcore <https://github.com/cnpm/cnpmcore/blob/master/app/core/service/PackageSyncerService.ts#L682>
 * return the diff versions from local to remote
 */
export declare class Package {
  constructor(data: Uint8Array)
  get name(): string | null
  get description(): string | null
  get readme(): string | null
  get time(): Record<string, string> | null
  get isUnpublished(): boolean
}
export type JsPackage = Package
