/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Package metadata document, sometimes informally called a "packument" or "doc.json".
 * @see <https://github.com/npm/registry/blob/main/docs/responses/package-metadata.md>
 */
export declare class Package {
  constructor(data: Uint8Array)
  /**
   * Find the diff versions between the local package and the remote package
   * source implement from cnpmcore <https://github.com/cnpm/cnpmcore/blob/master/app/core/service/PackageSyncerService.ts#L682>
   * return the diff versions from local to remote
   *
   * ### Parameters
   * - `Vec<String>`: the exists versions of the local package
   * ### Return
   * - `DiffResult`: the diff versions
   * - `String`: the version
   * - `(u32, u32)`: the version meta data position
   * ### Example
   * ```ts
   * const existsVersions = ['1.0.0', '1.0.1'];
   * const remotePkg = new Package(remoteBuffer);
   * const diff = remotePkg.diff(existsVersions);
   * console.log(diff);
   *
   * // read version meta data from buffer
   * const versionData = remoteBuffer.subarray(position[0], position[1]);
   * const version = JSON.parse(versionData);
   * ```
   * ### Output
   * ```ts
   * {
   *   added_versions: [
   *     ["1.1.0", [100992, 119796]],
   *     ["1.2.0", [119797, 138592]],
   *   ],
   *   removed_versions: [
   *     ["1.0.1", [100992, 119796]],
   *   ],
   * }
   * ```
   */
  diff(existsVersions: Array<string>): DiffResult
  get name(): string | null
  get description(): string | null
  get readme(): string | null
  get readmePosition(): [number, number] | null
  get time(): Record<string, string> | null
  get isUnpublished(): boolean
  get versions(): Record<string, Version>
  getLatestVersion(): Version | null
}

export interface Attestation {
  url?: string
  provenance?: Provenance
}

/** Bugs metadata */
export interface Bugs {
  url?: string
}

export interface DiffResult {
  addedVersions: Array<[string, [number, number]]>
  removedVersions: Array<string>
}

/**
 * Distribution metadata
 * @see <https://github.com/npm/registry/blob/main/docs/responses/package-metadata.md#dist>
 */
export interface Dist {
  /** the url of the tarball containing the payload for this package */
  tarball?: string
  /** the SHA-1 sum of the tarball */
  shasum?: string
  /**
   * since Apr 2017, string in the format <hashAlgorithm>-<base64-hash>,
   * refer the [Subresource Integrity](https://en.wikipedia.org/wiki/Subresource_Integrity) and [cacache](https://github.com/npm/cacache#integrity) package for more details
   */
  integrity?: string
  /** since Feb 2018, the number of files in the tarball, folder excluded */
  fileCount?: number
  /** since Feb 2018, the total byte of the unpacked files in the tarball */
  unpackedSize?: number
  signatures?: Array<Signature>
  attestations?: Attestation
}

/**
 * Human metadata
 * @see <https://github.com/npm/registry/blob/main/docs/responses/package-metadata.md#human>
 */
export interface Human {
  /** a freeform string name */
  name?: string
  /** an email address */
  email?: string
  /** a url for a web page with more information about the author */
  url?: string
}

export interface NpmOperationalInternal {
  tmp?: string
  host?: string
}

export interface PeerDependenciesMeta {
  optional?: boolean
}

export interface Provenance {
  predicateType?: string
}

export interface PublishConfig {
  registry?: string
  access?: string
}

/**
 * Repository metadata
 * @see <https://github.com/npm/registry/blob/main/docs/responses/package-metadata.md#repository>
 */
export interface Repository {
  type?: string
  url?: string
}

export interface Signature {
  sig?: string
  keyid?: string
}

/**
 * Version metadata
 * @see <https://github.com/npm/registry/blob/main/docs/REGISTRY-API.md#version>
 */
export interface Version {
  name?: string
  version?: string
  maintainers?: Array<Human>
  dist?: Dist
  funding?: Array<string>
  scripts?: Record<string, string>
  description?: string
  hasShrinkwrap?: boolean
  /** an array of operating systems supported by the package */
  os?: Array<string>
  /** an array of CPU architectures supported by the package */
  cpu?: Array<string>
  /** an array of libc supported by the package */
  libc?: Array<string>
}
